### ISSUE TITLE
Micronaut MQTT Guide is broken

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#1108] opened 2022-09-23 10:54 UTC
./gradlew micronautMqttBuild fails for me locally

**Comment by timyates** [comment] 2022-09-23 11:42
Passes for me...  Which JDK?  Do you have a Build Scan?

**Comment by sdelamo** [comment] 2022-09-23 12:59
```
% java --version
openjdk 11.0.16 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-11.0.16.8.1 (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.8.1 (build 11.0.16+8-LTS, mixed mode)

```

**Comment by timyates** [comment] 2022-09-23 13:15
https://ge.micronaut.io/s/6hckbggn5ycgg#infrastructure

Works on 11 after a clean with build caching turned off 🤔

**Comment by timyates** [comment] 2022-09-26 08:32
Closing this as I cannot reproduce it

**Closed as completed by timyates** 2022-09-26 08:32 UTC
Labels: bug
