### ISSUE TITLE
Add Oracle Cloud Tracing and Metrics Guide

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-guides#264] opened 2021-05-31 13:13 UTC

**Comment by burtbeckwith** [comment] 2022-05-18 19:58
Duplicate of https://github.com/micronaut-projects/micronaut-guides/issues/704 and https://github.com/micronaut-projects/micronaut-guides/issues/709

**Closed as completed by burtbeckwith** 2022-05-18 19:58 UTC
Labels: type: enhancement
